sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t mrshaker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true mrshaker/react-test npm test

after_success:
  - docker build -t mrshaker/multi-client ./client
  - docker build -t mrshaker/multi-nginx ./nginx
  - docker build -t mrshaker/multi-server ./server
  - docker build -t mrshaker/multi-worker ./worker
  